### ISSUE TITLE
Research API - Eventbrite (Meetup backup)

### ISSUE THREAD

**Issue by david-shao** [Fomono/prototype#3]

**Comment by jsaluja87** [comment]
Looked at this with Malleswari. Turns out that we don't need the OAuth to get the event list. For our app, just sending the request with 
https://www.eventbriteapi.com/v3//events/search/?token=<our_generated_token_id> was enough to get the information we need for now.
Will keep this open in case we need to do OAuth verification in the future

**Comment by jsaluja87** [comment]
This is done and submitted. Closing
